---
runners:
  hosts:
    cmput402ghrunner2:
      ansible_host: 2605:fd00:4:1001:f816:3eff:fe19:2d7f
      ansible_user: ubuntu
      become_user: root
      ansible_become: yes
      runners: 4
...